import type { Metadata } from "next";
import { Roboto_Slab, Khand, Lily_Script_One } from "next/font/google";
import "./globals.scss";
import "./portfunio.scss";

const roboto = Roboto_Slab({ subsets: ["latin"] });
const khand = Khand({
  subsets: ["latin"],
  weight: "400",
});
const lily = Lily_Script_One({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
